const PDFDocument = require('pdfkit');
const bwipjs = require('bwip-js');
const Consignment = require('../models/Consignment');

exports.generateLabel = async (req, res) => {
    try {
        const { consignmentId } = req.params;
        const consignment = await Consignment.findById(consignmentId);

        if (!consignment) {
            return res.status(404).json({ error: 'Consignment not found' });
        }

        // 4x6 Inch Label (288 x 432 points)
        const doc = new PDFDocument({
            size: [288, 432],
            margin: 10,
            autoFirstPage: true
        });

        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `inline; filename=label-${consignmentId}.pdf`);

        doc.pipe(res);

        // --- Borders ---
        doc.lineWidth(4).rect(5, 5, 278, 422).stroke(); // Heavy outer border
        doc.lineWidth(1);

        // --- Header Section (Service Type) ---
        doc.moveTo(5, 50).lineTo(283, 50).stroke(); // Horizontal divider

        doc.fontSize(24).font('Helvetica-Bold').text(consignment.serviceType.toUpperCase().substring(0, 1), 15, 15); // Big Letter (e.g., 'D', 'E')
        doc.fontSize(10).font('Helvetica-Bold').text('DTDC+', 15, 15, { align: 'right', width: 258 });
        doc.fontSize(8).font('Helvetica').text('EXPRESS DELIVERY', 15, 28, { align: 'right', width: 258 });

        // --- From Address ---
        doc.font('Helvetica-Bold').fontSize(6).text('FROM:', 12, 55);
        doc.font('Helvetica').fontSize(9).text(consignment.sender.name, 12, 65, { width: 150 })
            .fontSize(8).text(consignment.sender.address, { width: 160 })
            .text(`Ph: ${consignment.sender.phone}`);

        // --- To Address (Big) ---
        doc.moveTo(5, 120).lineTo(283, 120).stroke(); // Horizontal divider

        doc.font('Helvetica-Bold').fontSize(8).text('SHIP TO:', 12, 125);
        doc.font('Helvetica-Bold').fontSize(14).text(consignment.receiver.name, 20, 138);
        doc.font('Helvetica').fontSize(11).text(consignment.receiver.address, 20, 155, { width: 250 })
            .fontSize(14).font('Helvetica-Bold').text(`${consignment.receiver.destination} - ${consignment.receiver.pincode}`, 20, doc.y + 5);

        doc.fontSize(10).font('Helvetica').text(`Ph: ${consignment.receiver.phone}`, 20, doc.y + 5);

        // --- Routing / Sorting Code Area ---
        const sortY = 240;
        doc.moveTo(5, sortY).lineTo(283, sortY).stroke();

        doc.rect(5, sortY, 100, 60).stroke(); // Box for Destination Sort Code
        doc.fontSize(24).font('Helvetica-Bold').text(consignment.receiver.pincode.substring(0, 3), 15, sortY + 20);

        doc.fontSize(8).text(`WT: ${consignment.packageDetails.weight} KG`, 120, sortY + 10);
        doc.text(`DATE: ${new Date(consignment.bookingDate).toLocaleDateString()}`, 120, sortY + 25);
        doc.text(`DIMS: N/A`, 120, sortY + 40);

        // --- Barcode Section ---
        const barcodeY = 320;
        doc.moveTo(5, barcodeY).lineTo(283, barcodeY).stroke();

        try {
            const barcodeBuffer = await bwipjs.toBuffer({
                bcid: 'code128',
                text: consignment._id.toString(),
                scale: 3,
                height: 12,
                includetext: true,
                textxalign: 'center',
            });
            doc.image(barcodeBuffer, 24, barcodeY + 15, { width: 240, align: 'center' });
        } catch (e) {
            console.error(e);
            doc.text(consignment._id.toString(), 20, barcodeY + 20);
        }

        // --- Footer ---
        doc.fontSize(6).text('Generated by DTDC+ Enterprise Portal', 10, 415, { align: 'center', width: 268 });

        doc.end();

    } catch (error) {
        console.error('Label Generation Error:', error);
        res.status(500).json({ error: 'Failed to generate label' });
    }
};
